[project]
name = "oneforallmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "firebase>=4.0.1",
    "firebase-admin>=7.0.0",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.35.0",
]
